baseURL = 'https://grevyarlesp.github.io/homepage/'
languageCode = 'en-us'
title = "DDD"
theme = "xmin"
canonifyurls = true 

[params]
favicon    = "favicon.ico"

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'home'
  pre = "<i class='fa fa-heart'></i>"
  url = '/'
  weight = -110

[[menu.main]]
  identifier = 'blog'
  name = 'blog'
  pre = "<i class='fa fa-heart'></i>"
  url = '/blog'
  weight = -105

[markup.goldmark.renderer]
unsafe= true
